[phases.setup]
nixPkgs = ['nodejs_20', 'openssl']

[phases.install]
cmds = ['cd server && npm install']

[phases.build]
cmds = ['cd server && npx prisma generate']

[start]
cmd = 'cd server && node index.js'
